name: Build Windows Executable

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release'
        required: false
        default: false
        type: boolean

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Create Briefcase app
      run: |
        uv run briefcase create windows
        
    - name: Build Windows executable
      run: |
        uv run briefcase build windows
        
    - name: Package Windows app
      run: |
        uv run briefcase package windows
        
    - name: Test executable (basic startup)
      run: |
        # Test that the executable can start (will fail due to no display, but should validate basic structure)
        # This is a smoke test to ensure the build is structurally sound
        if (Test-Path "build/iso-pulse-gen/windows/app/src/Isochronic Pulse Generator.exe") {
          Write-Host "✅ Executable created successfully"
        } else {
          Write-Host "❌ Executable not found"
          exit 1
        }
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: isochronic-pulse-generator-windows
        path: |
          dist/Isochronic_Pulse_Generator-*.zip
          build/iso-pulse-gen/windows/app/**/*
        retention-days: 30
        
    - name: Create Release
      if: github.event.inputs.create_release == 'true' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Isochronic Pulse Generator v${{ github.run_number }}
        body: |
          ## Windows Portable Executable
          
          This release contains a portable Windows executable of the Isochronic Pulse Generator.
          
          ### Installation
          1. Download the ZIP file
          2. Extract to any folder
          3. Run `Isochronic Pulse Generator.exe`
          
          ### Features
          - ✅ Portable executable (no installation required)
          - ✅ Independent left/right channel configuration
          - ✅ Real-time audio generation with square wave modulation
          - ✅ Sample-accurate synchronization
          - ✅ Input validation and error handling
          
          ### Requirements
          - Windows 10 or later
          - Audio output device
          
        files: |
          dist/Isochronic_Pulse_Generator-*.zip
          build/iso-pulse-gen/windows/app/src/Isochronic Pulse Generator.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}